### PR TITLE
Update Readme.srt

### PR DESCRIPTION
**Pull request by coder579**
Fixed some typos.

### CODE REVIEW

**Comment by coder579** [comment]
So my PR won't be accepted?

**Comment by davehunt** [comment]
Accepted, approved, merged, and appreciated! Thank you @coder579!

**Comment by coder579** [comment]
Thank you so much!
You paved my way into the world of Open Source. It was my first ever Open Source contribution. Although it was quite small, but it was necessary to get me started.

**Comment by stephendonner** [comment]
Welcome, @coder579; I still can remember my first Open Source contribution back in 1998, which not only gave me a job, set me off on an amazing career; cheers!

**Pull request merged**
